[project]
name = "template-haskell-project"
version = "0.1.0"
description = "The Python environment for the `template-haskell-project` project"

requires-python = ">=3.10,<4.0"
dependencies = [
    "pre-commit (>=4.2.0,<5.0.0)",
    "icecream (>=2.1.4,<3.0.0)",
]
